# YOLOv5 Hyperparameter Evolution Results
# Best generation: 46
# Last generation: 58
#    metrics/precision,       metrics/recall,      metrics/mAP_0.5, metrics/mAP_0.5:0.95,         val/box_loss,         val/obj_loss,         val/cls_loss
#              0.69575,              0.70029,              0.67787,              0.23261,               0.0584,             0.017703,           0.00056724

lr0: 0.00976
lrf: 0.01126
momentum: 0.98
weight_decay: 0.0005
warmup_epochs: 2.7217
warmup_momentum: 0.91825
warmup_bias_lr: 0.07671
box: 0.0574
cls: 0.66898
cls_pw: 1.1835
obj: 1.247
obj_pw: 0.94747
iou_t: 0.2
anchor_t: 4.8806
fl_gamma: 0.0
hsv_h: 0.01258
hsv_s: 0.6785800000000001
hsv_v: 0.25458000000000003
degrees: 0.0
translate: 0.0859
scale: 0.75044
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.60805
mixup: 0.0
copy_paste: 0.0
anchors: 4.0582
