# YOLOv5 Hyperparameter Evolution Results
# Best generation: 41
# Last generation: 107
#    metrics/precision,       metrics/recall,      metrics/mAP_0.5, metrics/mAP_0.5:0.95,         val/box_loss,         val/obj_loss,         val/cls_loss
#              0.66629,              0.67049,              0.66767,              0.23038,             0.066449,             0.015692,             0.002483

lr0: 0.00975
lrf: 0.01223
momentum: 0.98
weight_decay: 0.00049
warmup_epochs: 2.3466
warmup_momentum: 0.95
warmup_bias_lr: 0.09656
box: 0.061989999999999996
cls: 0.48313
cls_pw: 0.91522
obj: 1.0006
obj_pw: 1.0572
iou_t: 0.2
anchor_t: 3.8314
fl_gamma: 0.0
hsv_h: 0.01608
hsv_s: 0.64058
hsv_v: 0.39538
degrees: 0.0
translate: 0.0792
scale: 0.41176999999999997
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.9812
mixup: 0.0
copy_paste: 0.0
anchors: 4.255
